language: python
python:
 - "3.5"
 - "3.6"
install:
 - pip3 install django coverage coveralls
before_script:
 - python3 ./PlaskBack/manage.py migrate
script:
 - coverage run --branch --source="./PlaskBack/ask" ./PlaskBack/manage.py test ask
 - coverage run --branch --source="./PlaskBack/location" ./PlaskBack/manage.py test location
 - coverage run --branch --source="./PlaskBack/user" ./PlaskBack/manage.py test user
after_success: coveralls 
