language: python
python:
 - "3.5"
 - "3.6"
install:
 - pip3 install django coverage coveralls
before_script:
 - cd backend
 - python3 manage.py migrate
script:
 - coverage run --branch --source="./ask" manage.py test ask
 - coverage run --branch --source="./location" manage.py test location
 - coverage run --branch --source="./user" manage.py test user
after_success: coveralls 
