# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 20, 2, 36, 43, 416360)),
        ),
    ]
