# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20171120_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 3, 8, 14, 933783)),
        ),
    ]
