# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_auto_20171120_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
