# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_auto_20171120_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='selAnswer',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ask.Answer'),
        ),
    ]
