# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userinfo_user'),
        ('ask', '0005_question_selanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ansUsers',
            field=models.ManyToManyField(default=None, null=True, related_name='answered', to='user.UserInfo'),
        ),
    ]
