# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_question_ansusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ansUsers',
            field=models.ManyToManyField(related_name='answered', to='user.UserInfo'),
        ),
    ]
