# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20171102_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='services',
            field=models.ManyToManyField(related_name='users', to='user.Service'),
        ),
    ]
