# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20171103_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='notify_freq',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='services',
            field=models.ManyToManyField(related_name='_userinfo_services_+', to='user.Service'),
        ),
    ]
