# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20171119_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='blocked',
            field=models.ManyToManyField(related_name='_userinfo_blocked_+', to='user.Service'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='services',
            field=models.ManyToManyField(related_name='users', to='user.Service'),
        ),
    ]
