# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20171102_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationL1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('persons', models.ManyToManyField(related_name='_locationl1_persons_+', to='user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='LocationL2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='location.LocationL1')),
                ('persons', models.ManyToManyField(related_name='_locationl2_persons_+', to='user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='LocationL3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='location.LocationL2')),
                ('persons', models.ManyToManyField(related_name='_locationl3_persons_+', to='user.UserInfo')),
            ],
        ),
    ]
