# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationl2',
            old_name='locations',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='locationl3',
            old_name='locations',
            new_name='parent',
        ),
    ]
